// <auto-generated />
using System;
using Kerekes_Denisa_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kerekes_Denisa_Proiect.Migrations
{
    [DbContext(typeof(Kerekes_Denisa_ProiectContext))]
    [Migration("20210105233327_ChocolateAssortment")]
    partial class ChocolateAssortment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kerekes_Denisa_Proiect.Models.Assortment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssortmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Assortment");
                });

            modelBuilder.Entity("Kerekes_Denisa_Proiect.Models.Chocolate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChocolateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChocolateSupplierID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7, 2)");

                    b.HasKey("ID");

                    b.HasIndex("ChocolateSupplierID");

                    b.ToTable("Chocolate");
                });

            modelBuilder.Entity("Kerekes_Denisa_Proiect.Models.ChocolateAssortment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssortmentID")
                        .HasColumnType("int");

                    b.Property<int>("ChocolateID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssortmentID");

                    b.HasIndex("ChocolateID");

                    b.ToTable("ChocolateAssortment");
                });

            modelBuilder.Entity("Kerekes_Denisa_Proiect.Models.ChocolateSupplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChocolateSupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ChocolateSupplier");
                });

            modelBuilder.Entity("Kerekes_Denisa_Proiect.Models.Chocolate", b =>
                {
                    b.HasOne("Kerekes_Denisa_Proiect.Models.ChocolateSupplier", "ChocolateSupplier")
                        .WithMany("Chocolates")
                        .HasForeignKey("ChocolateSupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kerekes_Denisa_Proiect.Models.ChocolateAssortment", b =>
                {
                    b.HasOne("Kerekes_Denisa_Proiect.Models.Assortment", "Assortment")
                        .WithMany("ChocolateAssortments")
                        .HasForeignKey("AssortmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kerekes_Denisa_Proiect.Models.Chocolate", "Chocolate")
                        .WithMany("ChocolateAssortments")
                        .HasForeignKey("ChocolateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
